
[dialogs]
confirm = "Confirm?"
error   = "Error"
ok      = "Ok"
cancel  = "Cancel"

[dialogs.chapter]
add     = "Add chapter"
edit    = "Edit chapter"
delete  = "Chapter “%1” will be deleted"
exists  = "Chapter already exists"
sort    = "Chapters will be sorted. This will change the book structure permanently."
compact = "Chapters will be renamed so no number will be missing in the middle. This will change the book structure permanently."

name   = "Key"
title  = "Title"
group  = "Group"

[dialogs.chapter.warnings]
duplicate    = "Another key with same name exists"
invalidkey   = "Key should contain only alphanumeric characters (a-z,A-Z,0-9)"
invalidgroup = "Group should contain only alphanumeric characters (a-z,A-Z,0-9)"


[dialogs.newbook]
new    = "Create a New Book"
title  = "Title"
author = "Author"
hint   = "You can recover the previous book with <b>File -> Recent sessions</b>"

[dialogs.newfirebook]
new    = "Create or load a New Book"
book   = "Book name"
getStarted = """Con questa funzione puoi collegare Magebook al tuo account Google, così da creare libri che si possono modificare in simultanea, proprio come i Documenti Google.<br>Prima di iniziare, dovrai collegare Magebook al tuo account <a href="../docs/it/index.html#/?id=progetti-collaborativi">seguendo questa guida</a>."""

[dialogs.shuffle]
title      = "Shuffle"
hint       = "Shuffle chapters with numeric key. You may choose to shuffle only chapters belonging to some groups, or to exclude chapters based on their flags. You should save a copy of your book before shuffling."
group      = "Group filter"
flags      = "Exclude flags"
savecopy   = "Save a copy"

[dialogs.lock]
title      = "Warning"
text       = "Another tab has written changes on this local session. If you overwrite, those changes will be lost. You can open a new session instead, and recover the other session with the <br><b>File -> Recent sessions</b> tool."
new        = "Open in new session"
overwrite  = "Overwrite"

[dialogs.graph]
loading    = "Loading graph..."
open       = "Open in new tab"
download   = "Download (as .svg)"


[navbar.file]
title       = "File"
new         = "New"
newFire     = "New collaborative"
share       = "Share"
open        = "Open..."
save        = "Save"
recover     = "Latest sessions"
recoverFire = "Collaborative sessions"

[navbar.book]
title   = "Book"
graph   = "View graph"
shuffle = "Shuffle"
sort    = "Sort chapters"
compact = "Compact chapters"

[navbar.export]
title = "Export"
docx  = "Word (.docx)"
html  = "Website (.html)"
fodt  = "Libreoffice (.fodt)"
xlgc  = "LibroGameCreator 3"
json  = "Json"
vuejs = "Vue.js"

others       = "Others (ebook, Android app, ...)"
otherslink   = "https://librogamesland.github.io/magebook/index.html#/?id=other-formats"
settings     = "Export settings"
settingslink = "https://librogamesland.github.io/magebook/index.html#/?id=settings"

[navbar.help]
title     = "Help"
guide     = "Guide"
guidefile = "https://librogamesland.github.io/magebook" 
forum     = "Lgl forum"
about     = "About"

[navbar.buttons]
fullscreen = "Fullscreen" 
darktheme  = "Toggle dark/light theme"


[sidemenu]
toggle    = "Toggle sidemenu"
chapters  = "Chapters"
allgroup  = "All chapters"
allgrouperrors  = "Without links from/to"
allgrouporphanlinks  = "With orphan links"
linkshere = "Links to"

[sidemenu.actions]
goback   = "Go back"
add      = "Add entity (ctrl+R)"
edit     = "Edit entity (ctrl+E)"
delete   = "Delete entity (ctrl+D)"


[editor.buttons]
find = "Find (ctrl+F)"
undo = "Undo last change (ctrl+Z)"
redo = "Redo last change (ctrl+shift+Z)"
quicklink = "Link to the first avaiable chapter (ctrl+K)"
link      = "Add link (ctrl+L)"


[about]
contact = "Contact me"
text = """
Magebook is a gamebook web editor developed by <b>Luca Fabbian</b> with support of Lgl community."""


[books]
local = """
# Book title
author: Name and Surname


### 1
Chapter example. You may edit this chapter thanks to the buttons on the right sidemenu.
This is a link going to [2]. Links may also be  [Text](#chapter).


### Chapter with a long title {#2}
This is the second chapter. Chapters may include *italic* or **bold** text. <b>Bold</b>, <i>italic</i>, and <u>underline</u> are fine as well. You may add meta text with ` ` like `TODO: edit this chapter`.
"""
fire = """
# %1
author: Name and Surname


### 1
Questo è un libro collaborativo memorizzato sul tuo account Google e che può essere modificato da più persone contemporaneamente. Salva questa pagina fra i segnalibri del tuo browser e inviala a chi vuoi, vedrai le modifiche sincronizzate in tempo reale.
"""

[app]
openlocal    = "Create or open local file"
openfire     = "Create or access collaborative book"
chooseother  = "Choose another book"

[dialogs.version]
title = "New version - "
text  = 'Discover more on the <a ref="_blank" href="https://librogamesland.github.io/magebook/#/?id=releases">guide page</a>.'
"1.0" = "Initial release." 
"1.1" = "Added short links format [number] and 'disableShortLinks: true'.<br>Links to orphan chapters are highlighted in the sidemenu.<br>General restyle.<br>New Website export.<br>Bug fixes." 